### ISSUE TITLE
GPIO.pinMode( *args) didn't alter Pin 27 - 40 of Rpi B+

### ISSUE THREAD

**Issue by ChrSchultz** [Gadgetoid/WiringPi2-Python#21]
<code> import os </code>
<code>from wiringpi2 import GPIO </code>
<code> g = GPIO (3)</code>
<code> os.system('gpio -1 readall')</code>
<code>g.pinMode(28, g.OUTPUT)</code>
<code>os.system('gpio readall')</code>
if you compare the output of "gpio readall" call1 and call2 there are the same outputs... "gpio -1 mode 28 OUT" works fine. 
please update your library for B+ support.

**Comment by Gadgetoid** [comment]
This should have been fixed by https://github.com/Gadgetoid/WiringPi2-Python/commit/5ad727f92b5bb8614c7d8a72dd98123bfeb100b0
