### ISSUE TITLE
Setting up mcp23017 on busy pins: raise exception instead of exiting

### ISSUE THREAD

**Issue by elegantandrogyne** [Gadgetoid/WiringPi2-Python#26]
Whenever I set up mcp23017 with `wiringpi2.mcp23017Setup(65, 0x20) ` twice on the same pin base, for example:
```
#!/usr/bin/python
import wiringpi2

def Foo(object):
  def __init__(self):
    pass
  def __enter__(self):
    wiringpi2.mcp23017Setup(65, 0x20)
    for pin in range(65, 82):
      wiringpi2.pinMode(pin, 1)
      wiringpi2.digitalWrite(pin, 0)
  def __exit__(self, *args):
    pass

foo = Foo()

# call it now - everything okay...
with foo:
  pass

# do something else...

# call it again - bang!
with foo:
  pass
```
 my program exits with a message:
`wiringPiNewNode: Pin 65 overlaps with existing definition`
It'd be a lot better if wiringpi2-python raised an exception instead, so I could catch it with a try/except clause.

**Comment by willprice** [comment]
Why not just call it initially? Or deallocate the pin in `__exit__`
