### ISSUE TITLE
Python 3 compatability

### ISSUE THREAD

**Issue by howitzer-88** [Gadgetoid/WiringPi2-Python#35]
Thanks for your great work, Please add a #define for PyUnicode_FromStringAndSize to wiringpi_wrap.c this will allow compatibility with PyString_FromStringAndSize. 

that will fix ImportError: /usr/lib/python3.5/site-packages/wiringpi2-1.1.1-py3.5-linux-armv6l.egg/_wiringpi2.cpython-35m-arm-linux-gnueabihf.so: undefined symbol: PyString_FromStringAndSize 

I have attached modified wiringpi_wrap.c with the fix. It's on line 738.
[wiringpi_wrap.txt](https://github.com/Gadgetoid/WiringPi2-Python/files/149693/wiringpi_wrap.txt)

**Comment by Gadgetoid** [comment]
wiringpi_wrap.c is generated entirely by SWIG ( 2.0, or possibly now 3.0 ) so we need to work within the confines of that to make fixes/changes to the (generated) bindings.

I will investigate!

**Comment by Gadgetoid** [comment]
This appears to be fixed in: https://github.com/WiringPi/WiringPi-Python/commit/2fb6b4999527f2e491d34a58f7eb87d97ffa050e
