### ISSUE TITLE
Interrupt causes TypeError

### ISSUE THREAD

**Issue by pacmac** [Gadgetoid/WiringPi2-Python#8]
With the following code, the interrupt generates a segmentation fault.

	#!/usr/bin/env python2
	import wiringpi2
	import time
		
	def my_int():
		print('Interrupt')
	
	wpi = wiringpi2.GPIO(wiringpi2.GPIO.WPI_MODE_PINS)
	wpi.pullUpDnControl(4,wpi.PUD_UP) 
	wpi.wiringPiISR(4, wpi.INT_EDGE_BOTH, my_int())
	while True:
		time.sleep(1)
		print('Waiting...')

	Waiting...
	Waiting...
	Waiting...
	Waiting...
	Segmentation fault

If I callback without the "()" then I get another error:

	wpi.wiringPiISR(4, wpi.INT_EDGE_BOTH, my_int)

    > TypeError: in method 'wiringPiISR', argument 3 of type 'void (*)(void)'

What am I doing wrong ???

This is also reported here: http://stackoverflow.com/questions/19831498/raspberrypi-python-wiringpi2-interrupt-syntax

**Comment by tasptz** [comment]
Shouldn't this be possible through CFUNCTYPE (https://docs.python.org/2/library/ctypes.html#ctypes.CFUNCTYPE)? However I get the same error.

**Comment by nalajcie** [comment]
Hi,
I've just created pull request implementing this functionality: https://github.com/WiringPi/WiringPi2-Python/pull/24
